hmcts/pip-shared-infrastructures

- .github/workflows/ci.yml
- Jenkinsfile_CNP
- README.md
- tf-kv-secrets.tf
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> update Read Me

- Jenkinsfile_parameterized
Add the sandbox jenkins file
```
[ ] Yes
[ X ] No
```
> Add sbox jenkins file

- tf-db-main.tf
- tf-db-secrets.tf
https://tools.hmcts.net/jira/browse/PUB-938
Add new shared postgressql
```
[ ] Yes
[ X ] No
```
> PUB-938 Add shared PostgresSql Server

- infrastructure/resources/product-policy.xml
- main.tf
- tf-kv-secrets.tf
change resources names, so length is below limit for sbox and prod
```
[ ] Yes
[ X ] No
```
> change resource name

- main.tf
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> add env to storage account

- tf-kv-main.tf
https://tools.hmcts.net/jira/browse/PUB-951
Create Managed Identities from this pipeline
```
[ X ] Yes - We are scheduling a time where flux will not have the correct MIs and we need to update them
[ ] No
```
> PUB-951 create MIs from this pipeline

- tf-sa-main.tf
https://tools.hmcts.net/jira/browse/PUB-1011
In SA, set blob public access and added new container with CORS rule. 
```
[ ] Yes
[x] No
```
> PUB-1011 Add container in storage account with public access

- tf-sa-main.tf
https://tools.hmcts.net/jira/browse/PUB-1011
Set data protection to true in SA module so that the CORS rule is created. 
This is in addition to other pull requests that have already been merged:
https://github.com/hmcts/pip-shared-infrastructures/pull/11
https://github.com/hmcts/cnp-module-storage-account/pull/23
```
[ ] Yes
[x] No
```
> PUB-1011 Set data protection to true in blob storage

- tf-sa-main.tf
For the Shutter Page to work we need a storage account in our Resource Group created.
```
[ ] Yes
[ X ] No
```
> Add Shutter Storage Account

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- main.tf
- providers.tf
- tf-aa-main.tf
- tf-kv-secrets.tf
- variables.tf
https://tools.hmcts.net/jira/browse/PUB-1021
Added b2c secrets to kv-secrets file, replace instances of OTP with B2C.
```
[ ] Yes
[x] No
```
> PUB-1021 Added b2c secrets to kv-secrets file, replace instances of OTP with B2C

- main.tf
- tf-kv-b2c-main.tf
https://tools.hmcts.net/jira/browse/PUB-1145
Add new KV for APIM
Add new MI for APIM
```
[ ] Yes
[ x ] No
```
> PUB-1145 - Add new APIM KV and MI

- Jenkinsfile_parameterized
- tf-db-secrets.tf
- tf-sa-main.tf
Due to an issue with database setup, we need to hardcode the secrets for Data Management.
```
[ ] Yes
[ x ] No
```
> Add fix for Data Management Secrets

- demo.tfvars
- dev.tfvars
- ithc.tfvars
- prod.tfvars
- sbox.tfvars
- stg.tfvars
- test.tfvars
- tf-kv-main.tf
- tf-kv-secrets-b2c.tf
- tf-kv-secrets-bootstrap.tf
- tf-kv-secrets.tf
- tf-sa-main.tf
- variables.tf
https://tools.hmcts.net/jira/browse/PUB-1151
Add the static B2C extension app client ID
```
[ ] Yes
[ x ] No
```
> PUB-1151 Add b2c extension client id and move secrets out

- tf-apim-subscription.tf
- tf-kv-apim-secrets.tf
PUB-1149
Add the subscription key to the key vault
```
[ ] Yes
[ x ] No
```
> PUB-1149 - add subscripton key to key vault

- tf-sa-main.tf
[PUB-1279](https://tools.hmcts.net/jira/browse/PUB-1279)
Create new container for storage account
```
[ ] Yes
[ x ] No
```
> PUB-1279 Create new Container

- Jenkinsfile_CNP
- tf-kv-access.tf
- tf-kv-main.tf
- variables.tf
PUB-1068
Give the Github app access to the Key Vault
```
[ ] Yes
[ x ] No
```
> PUB-1068 - Add Github Runner Permissions

- demo.tfvars
- dev.tfvars
- ithc.tfvars
- sbox.tfvars
- stg.tfvars
- test.tfvars
- tf-b2c-apps-fe.tf
PUB-961
Add new extension app ID
Add frontend new permissions
```
[ ] Yes
[ x ] No
```
> PUB-961 - Add B2C changes

- tf-b2c-main.tf
- tf-kv-secrets-bootstrap.tf
- tf-kv-secrets.tf
PUB-961 
Add new B2C URL
```
[ ] Yes
[ x ] No
```
> PUB-961 - Add new B2C URL

- tf-b2c-main.tf
PUB-961 
need to remove the url suffix before use.
```
[ ] Yes
[ x ] No
```
> PUB-961 - replace url suffix

- tf-sa-main.tf
PUB-961 
Add dynamic B2C url to cors
```
[ ] Yes
[ x ] No
```
> PUB-961 - Add B2C Domain to CORS

- tf-aa-secret-rotation.tf
PUB-961
Hardcode in the Jenkins Client ID
```
[ ] Yes
[ x ] No
```
> PUB-961 - Add Client ID for Jenkins

- infrastructure/resources/product-policy.xml
update rate limits for APIM Product
```
[ ] Yes
[ x ] No
```
> update rate limits for APIM Product

- dev.tfvars
- prod.tfvars
- stg.tfvars
- test.tfvars
- tf-kv-apim-access.tf
PUB-1302
Add HMI Managed Identities to Key Vault
```
[ ] Yes
[ x ] No
```
> PUB-1302 - Add HMI Managed Identities to Key Vault

- demo.tfvars
- dev.tfvars
- ithc.tfvars
- prod.tfvars
- sbox.tfvars
- stg.tfvars
- test.tfvars
- tf-aa-main.tf
- tf-aa-secret-rotation.tf
- variables.tf
Need to give the MI access to the automation account
Make jenkin client id a var as sbox is different.
```
[ ] Yes
[ x ] No
```
> Correct MI and access

- infrastructure/modules/kv_secrets/main.tf
- tf-app-insights.tf
- tf-kv-secrets.tf
Create App insights for pip
```
[ ] Yes
[ x ] No
```
> Create App insights

- Jenkinsfile_CNP
- prod.tfvars
PUB-961
Add production extension app for the new B2C
```
[ ] Yes
[ x ] No
```
> PUB-961 Add production extension app

- tf-kv-secrets-bootstrap.tf
https://tools.hmcts.net/jira/browse/PUB-1269
Added new team email secret to the bootstrap array
```
[ ] Yes
[ x ] No
```
> PUB 1269 - Add new team email secret

- tf-apim-main.tf
Allow deployment of APIM to Production
```
[ ] Yes
[ x ] No
```
> Add APIM to Production

- dev.tfvars
- stg.tfvars
- test.tfvars
- tf-b2c-main.tf
PUB-1061
Add B2C URL and endpoints
```
[ ] Yes
[ x ] No
```
> PUB-1061 - Add b2c url

- tf-b2c-main.tf
- tf-kv-secrets.tf
PUB-1061 
Update B2C URLs
```
[ ] Yes
[ x ] No
```
> PUB-1061 - Update b2c url

- infrastructure/resources/b2c-polices/admin-login.html
- infrastructure/resources/b2c-polices/change.html
- infrastructure/resources/b2c-polices/login.css
- infrastructure/resources/b2c-polices/login.html
- infrastructure/resources/b2c-polices/reset-pw.css
- infrastructure/resources/b2c-polices/reset-pw.html
- infrastructure/resources/b2c-polices/reset.html
- main.tf
- tf-sa-b2c.tf
[PUB-1393](https://tools.hmcts.net/jira/browse/PUB-1393)
replace b2c files placeholders
split files and images in TF.
please also review https://tools.hmcts.net/confluence/display/PUBH/Add+Placeholder+to+B2C+Files
```
[ ] Yes
[ x ] No
```
> PUB-1393 - replace content on b2c files

- tf-kv-secrets.tf
Add base b2c url secrets
```
[ ] Yes
[ x ] No
```
> Add base b2c url secrets

- infrastructure/resources/b2c-polices/admin-login.html
- infrastructure/resources/b2c-polices/change.html
- infrastructure/resources/b2c-polices/login.html
- infrastructure/resources/b2c-polices/reset-pw.html
- infrastructure/resources/b2c-polices/reset.html
https://tools.hmcts.net/jira/browse/PUB-1329
Updated the footers with additional text to go under the licence for all b2c html pages.
```
[ ] Yes
[x] No
```
> PUB-1329 Footer legal OGL wording update

- infrastructure/resources/b2c-polices/admin-login.html
- infrastructure/resources/b2c-polices/change.html
- infrastructure/resources/b2c-polices/login.css
- infrastructure/resources/b2c-polices/login.html
- infrastructure/resources/b2c-polices/reset-pw.html
- infrastructure/resources/b2c-polices/reset.html
https://tools.hmcts.net/jira/browse/PUB-1284
Removing nav bar links and replacing with single nav bar "Home" link.
Also implemented changes for PUB-1351 (https://tools.hmcts.net/jira/browse/PUB-1351)
```
[ ] Yes
[x] No
```
> PUB-1284 Fixing nav bar on admin login

- tf-kv-secrets-bootstrap.tf
- tf-kv-secrets.tf
added courtel api secret
```
[ ] Yes
[ ] No
```
> added courtel to tf kv secrets

- tf-kv-secrets.tf
Add the Active Directory URL for B2C
```
[ ] Yes
[ x ] No
```
> Add AD URL

- infrastructure/resources/b2c-polices/admin-mfa.css
- infrastructure/resources/b2c-polices/admin-mfa.html
- infrastructure/resources/b2c-polices/login.css
https://tools.hmcts.net/jira/browse/PUB-1372
Updated templates and styling
```
[ ] Yes
[x] No
```
> PUB-1372 MFA admin

- infrastructure/resources/b2c-polices/admin-login.html
- infrastructure/resources/b2c-polices/change.html
- infrastructure/resources/b2c-polices/login.html
- infrastructure/resources/b2c-polices/reset-pw.html
- infrastructure/resources/b2c-polices/reset.html
https://tools.hmcts.net/jira/browse/PUB-1428
altered home link on all pages.
```
[ ] Yes
[ x] No
```
> PUB-1428 - altered home button link

- tf-kv-secrets-bootstrap.tf
Add Courtel secret
```
[ ] Yes
[ x ] No
```
> Add new Secret from Bootstrap

- tf-kv-secrets.tf
Correct B2C AD Url
```
[ ] Yes
[ x ] No
```
> Correct B2C AD Url

- tf-b2c-main.tf
- tf-kv-access.tf
- tf-kv-secrets.tf
https://tools.hmcts.net/jira/browse/PUB-942
Added permissions to KV
```
[ ] Yes
[x] No
```
> PUB-942 - Updated KV access

- tf-kv-access.tf
https://tools.hmcts.net/jira/browse/PUB-942
Updated object ID for CFT jenkins
```
[ ] Yes
[x] No
```
> Updated object ID

- tf-sa-main.tf
https://tools.hmcts.net/jira/browse/PUB-1586
Added code to create new blob storage container called publications.
```
[ ] Yes
[x] No
```
> PUB-1586 Blob storage container

- Jenkinsfile_parameterized
- tf-kv-sdp-main.tf
https://tools.hmcts.net/jira/browse/PUB-1595
Create a new KV for the SDP details
```
[ ] Yes
[x] No
```
> PUB-1595 - Creation of a new KV for SDP

- infrastructure/resources/b2c-polices/admin-mfa.html
- infrastructure/resources/b2c-polices/login.html
- infrastructure/resources/b2c-polices/reset-pw.html
https://tools.hmcts.net/jira/browse/PUB-1684
Align footers with rest of the service.
```
[ ] Yes
[x] No
```
> PUB-1684 Align footers

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
> [PREVIEW] Test PR 

- tf-kv-secrets.tf
https://tools.hmcts.net/jira/browse/PUB-1812
Fix issue with 'keepers' for session secret
```
[ ] Yes
[x] No
```
> PUB-1812 - Fix session secret

- infrastructure/resources/b2c-polices/admin-mfa.html
- infrastructure/resources/b2c-polices/login.css
- infrastructure/resources/b2c-polices/login.html
- infrastructure/resources/b2c-polices/reset-pw.css
- infrastructure/resources/b2c-polices/reset-pw.html
https://tools.hmcts.net/jira/browse/PUB-1761
Removed not found resources on Azure pages
```
[ ] Yes
[x] No
```
> PUB-1761 Removed not found resources on Azure pages

- infrastructure/resources/b2c-polices/reset-pw.css
- infrastructure/resources/b2c-polices/reset-pw.html
https://tools.hmcts.net/jira/browse/PUB-1949
Add password advice text and use h2 for heading
```
[ ] Yes
[x] No
```
> PUB-1949 Add password advice text and use h2 for heading

- infrastructure/resources/b2c-polices/reset-pw.html
https://tools.hmcts.net/jira/browse/PUB-1951
Password reset error
```
[ ] Yes
[x] No
```
> PUB-1951 Password reset error

- infrastructure/resources/b2c-polices/admin-mfa.css
- infrastructure/resources/b2c-polices/reset-pw.css
https://tools.hmcts.net/jira/browse/PUB-1935
Updated Cancel and Send new code links to blue rather than buttons
```
[ ] Yes
[x] No
```
> PUB-1935 - Added blue links

- infrastructure/resources/b2c-polices/login.css
- infrastructure/resources/b2c-polices/login.html
https://tools.hmcts.net/jira/browse/PUB-1931
Move forgot password link
```
[ ] Yes
[ ] No
```
> PUB-1931 Move forgot password link

- tf-sa-b2c.tf
https://tools.hmcts.net/jira/browse/PUB-1927
Add file extensions for font files
```
[ ] Yes
[x] No
```
> PUB-1927 Add file extensions for font files

- infrastructure/resources/b2c-polices/admin-mfa.html
- infrastructure/resources/b2c-polices/login.html
- infrastructure/resources/b2c-polices/reset-pw.html
https://tools.hmcts.net/jira/browse/PUB-1930
Azure pages beta survey feedback
```
[ ] Yes
[x] No
```
> PUB-1930 Azure pages beta survey feedback

- tf-redis-main.tf
- tf-sa-main.tf
https://tools.hmcts.net/jira/browse/PUB-1792
Added pip MI permissions to the storage account, in prep for 1793 which will switch to using the MI
```
[ ] Yes
[x] No
```
> PUB-1792 - Added MI permissions

- tf-kv-cp-main.tf
N/A
Added new KV for Common Platform in PIP
```
[ ] Yes
[x] No
```
> Add new kv pip

- tf-kv-cp-secrets.tf
N/A
Added tenant ID into KV for Common Platform
```
[ ] Yes
[x] No
```
> Added tenant ID into KV

- tf-kv-secrets.tf
https://tools.hmcts.net/jira/browse/PUB-2084
Added app insights connection string for java
```
[ ] Yes
[x] No
```
> PUB-2084 - Added App Insights connection string for Java

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/PUB-1763
Auto sync demo environment
```
[ ] Yes
[x] No
```
> PUB-1763 - Auto sync demo env

- tf-apim-main.tf
https://tools.hmcts.net/jira/browse/PUB-1763
Enabled APIM for demo
```
[ ] Yes
[x] No
```
> PUB-1763 - Enable demo in APIM

- .github/dependabot.yml
- .github/renovate.json
https://tools.hmcts.net/jira/browse/PUB-2144
Updated pipeline to use renovate
```
[ ] Yes
[x] No
```
> PUB-2124 - Updated to renovate

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- tf-crime-connection-mi.tf
- variables.tf
https://tools.hmcts.net/jira/browse/PUB-2159
Created federated credential for linking the PIP crime MI with the crime cluster.
```
[ ] Yes
[x] No
```
> PUB-2159 MIs for Crime

- tf-crime-connection-mi.tf
https://tools.hmcts.net/jira/browse/PUB-2159
Federated identity for crime, update RG.
```
[ ] Yes
[x] No
```
> PUB-2159 MI for crime

- tf-kv-secrets.tf
https://tools.hmcts.net/jira/browse/PUB-2107
Rotate session secret
```
[ ] Yes
[x] No
```
> PUB-2107 - Updated secret

- tf-redis-v6-main.tf
Added family for redis
```
[ ] Yes
[x] No
```
> PUB-2194 Updated family for redis

- tf-b2c-main.tf
- tf-sa-b2c.tf
https://tools.hmcts.net/jira/browse/PUB-2117
Updated B2C Domains
```
[ ] Yes
[x] No
```
> PUB-2117 - Added B2C Domains

- tf-b2c-main.tf
https://tools.hmcts.net/jira/browse/PUB-2117
Updated Staging URLs
```
[ ] Yes
[x] No
```
> PUB-2117 - Added new B2C Domains

- tf-redis-v6-main.tf
N/A
Fix redis issue with memory in lower environments
```
[ ] Yes
[x] No
```
> Fixed redis in lower environments

- .github/workflows/terraform_format.yml
https://tools.hmcts.net/jira/browse/PUB-2182
Add terraform_format.yml
```
[ ] Yes
[X] No
```
> PUB-2182 add terraform_format.yml

- .github/workflows/terraform_format.yml
- README.md
Merge code freeze branch to Master
```
[ ] Yes
[x] No
```
> Merge code freeze branch to Master

- tf-sa-b2c.tf
https://tools.hmcts.net/jira/browse/PUB-2317
Added MD5 to update logo
```
[ ] Yes
[x] No
```
> PUB-2317 - Added content MD5 for image files

- main.tf
- tf-kv-secrets.tf
https://tools.hmcts.net/jira/browse/PUB-2297
Removed unneeded secrets + updated expiry
```
[ ] Yes
[x] No
```
> PUB-2297 - Removed unneeded secrets + updated expiry

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- README.md
- main.tf
- tf-crime-connection-mi.tf
- variables.tf
https://tools.hmcts.net/jira/browse/PUB-2343
Updated perf test
```
[ ] Yes
[x] No
```
> PUB-2343 - Perf Test

- tf-b2c-main.tf
- tf-sa-main.tf
https://tools.hmcts.net/jira/browse/PUB-2298
Updated CORS rules config in test
```
[ ] Yes
[x] No
```
> PUB-2298 - Updated cors rules - test

- tf-b2c-main.tf
- tf-sa-main.tf
https://tools.hmcts.net/jira/browse/PUB-2298
Updated CORS change
```
[ ] Yes
[x] No
```
> PUB-2298 - Updated cors rules

- tf-aa-secret-rotation.tf
https://tools.hmcts.net/jira/browse/PUB-2369
Merge into ITHC env
```
[ ] Yes
[x] No
```
> PUB-2369 - App rotation - ITHC env

- tf-aa-secret-rotation.tf
https://tools.hmcts.net/jira/browse/PUB-2369
Fix issue with app rotation
```
[ ] Yes
[x] No
```
> PUB-2369 - App rotation

- providers.tf
https://tools.hmcts.net/jira/browse/PUB-2375
Dependency updates
```
[ ] Yes
[x] No
```
> PUB-2375 - Dependency updates

- test.tfvars
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/PUB-2497
```
[ ] Yes
[X] No
```
> PUB-2497- Downgraded test non-prod environment from Standard to Basic

- tf-kv-secrets-bootstrap.tf
https://tools.hmcts.net/jira/browse/PUB-1566
Add crime idam credentials secrets in bootstrap keyvault
[ ] Yes
[x] No
> PUB-1566 Add Crime Idam Credentials

- tf-kv-secrets.tf
https://tools.hmcts.net/jira/browse/PUB-2340
Handle multiple FE session keys
```
[ ] Yes
[x] No
```
> PUB-2340 - Add new session key secret

- tf-kv-secrets.tf
Reverts hmcts/pip-shared-infrastructures#181
> Revert "PUB-2340 - Add new session key secret"

- tf-kv-secrets.tf
Reverts hmcts/pip-shared-infrastructures#185
> Revert "Pub 2340 b"

- tf-kv-secrets.tf
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> add new session key

- tf-kv-secrets.tf
https://tools.hmcts.net/jira/browse/PUB-2340
Add new session key to kv
```
[ ] Yes
[x] No
```
> PUB-2340 - Add new session key

- providers.tf
- tf-kv-secrets-bootstrap.tf
https://tools.hmcts.net/jira/browse/PUB-2630
Added SSO bootstrap secrets
```
[ ] Yes
[x] No
```
> PUB-2630 - Updated infra for SSO

- infrastructure/resources/b2c-polices/admin-mfa-cy-GB.html
- infrastructure/resources/b2c-polices/admin-mfa-en.html
- infrastructure/resources/b2c-polices/login-cy-GB.html
- infrastructure/resources/b2c-polices/login-en.html
- infrastructure/resources/b2c-polices/login.css
- infrastructure/resources/b2c-polices/reset-pw-cy-GB.html
- infrastructure/resources/b2c-polices/reset-pw-en.html
- infrastructure/resources/b2c-polices/reset-pw.css
https://tools.hmcts.net/jira/browse/PUB-2610
Update service navigation styling
```
[ ] Yes
[x] No
```
> PUB-2610 Update service navigation styling

- infrastructure/resources/b2c-polices/admin-mfa-cy-GB.html
- infrastructure/resources/b2c-polices/login-cy-GB.html
- infrastructure/resources/b2c-polices/reset-pw-cy-GB.html
https://tools.hmcts.net/jira/browse/PUB-2698
Updated language in B2C files
```
[ ] Yes
[x] No
```
> PUB-2698 - Updated Language

- infrastructure/resources/b2c-polices/admin-mfa-cy-GB.html
- infrastructure/resources/b2c-polices/login-cy-GB.html
- infrastructure/resources/b2c-polices/reset-pw-cy-GB.html
N/A
Merge freeze to master
```
[ ] Yes
[x] No
```
> Merge freeze to master

- main.tf
https://tools.hmcts.net/jira/browse/PUB-2771
Updated expiry refresh
```
[ ] Yes
[x] No
```
> PUB-2771 - KV Expiry Refresh

- tf-kv-secrets-bootstrap.tf
https://tools.hmcts.net/jira/browse/PUB-2555
Removed copying of staging bootstrap secret app-insights-nodejs-connection-string
```
[ ] Yes
[x] No
```
> PUB-2555 Removed copying of staging bootstrap secret app-insights-nodejs-connection-string

- providers.tf
https://tools.hmcts.net/jira/browse/PUB-2959
Dependency Updates
```
[ ] Yes
[x] No
```
> PUB-2959 - Dependency Updates
